### ISSUE TITLE
Left arrow on controller often misses button down

### ISSUE THREAD

**Issue by jmzjmzjmz** [adafruit/Bluefruit_LE_Connect_v2#11]
Then on physically releasing the arrow, it sends out "pressed" & "released" sequentially.

Bluefruit LE Connect V2.2.0
ios10.1
Arduino BluefruitLE 1.9.3

Seems to happen more often in portrait than landscape

**Comment by microbuilder** [comment]
We can't reproduce this here ... what phone are you using?

**Comment by antonio-openroad** [comment]
I finally could reproduce it on iPhone. On iPad it works fine.
The left arrow button touch down conflicted with the swipe-to-go-back gesture

Thanks for reporting the issue
