### ISSUE TITLE
Installing on iPhone – Paid developer account required?

### ISSUE THREAD

**Issue by braitsch** [adafruit/Bluefruit_LE_Connect_v2#12]
Hello, I just tried to install this on my iPhone via xCode 8.0 and I'm getting an error:
````
Your account does not have sufficient permissions to modify containers.
````
I'm assuming I'm getting this error because I'm using a free iOS developer account.
Is it possible to run/test this on an iDevice without a paid developer account?

Many thanks.

**Comment by antonio-openroad** [comment]
I have not tested with a free developer account but you could try to disabling the iCloud Capability. 
Project Settings -> Targets -> iOS -> Capabilities -> iCloud
Custom firmware updates will stop working though
