### ISSUE TITLE
'Adafruit_Bluefruit_LE_Connect-Swift.h' file not found

### ISSUE THREAD

**Issue by pgebhard** [adafruit/Bluefruit_LE_Connect_v2#13]
Bluefruit_LE_Connect_v2-master/bluefruitconnect/Utils/Updater/FirmwareUpdater.m:16:13: 'Adafruit_Bluefruit_LE_Connect-Swift.h' file not found

Bluefruit_LE_Connect_v2-master/bluefruitconnect/Utils/Updater/ReleasesParser.m:13:9: 'Adafruit_Bluefruit_LE_Connect-Swift.h' file not found

I don't believe these files exist in the project.

**Comment by antonio-openroad** [comment]
That file should be autogenerated by Xcode.
Make sure you are using Xcode 8.0 or 8.1 and that the build setting  "Objetive-C Generated Interface Header Name" is set to "Adafruit_Bluefruit_LE_Connect-Swift.h"
