### ISSUE TITLE
iPhone differs from iPad

### ISSUE THREAD

**Issue by adamstener** [adafruit/Bluefruit_LE_Connect_v2#19]
On the iPhone, if you filter out the devices based on signal strength, anything not matching the filter is removed from the list. If you use the same parameters on the iPad, it seems like anything advertised with terrible signal strength still makes the list. I would assume this has to do with an RSSI coming through that's a false positive value, and somehow this is managed on the phone differently than the iPad.

**Comment by adamstener** [comment]
On the iPhone, I can dial down the signal strength window, that allows me to see how close I have to get to a device in order to pass that threshold.  On the iPad, there are too many things in the list to have this same effect, so I'm unable to perform the same tests, which would be extremely helpful if I could.

**Comment by antonio-openroad** [comment]
Thanks for reporting it. 
It looks that it is related to how undefined RSSI values are handled

**Comment by adamstener** [comment]
In my BLE implementation, I sometimes get arbitrarily large values, like 128, which need to be filtered out.  Was kind of thinking it could be this.

**Comment by adamstener** [comment]
The latest commit has solved the issue, thanks much.
