### ISSUE TITLE
Multiple UART connections

### ISSUE THREAD

**Issue by microbuilder** [adafruit/Bluefruit_LE_Connect_v2#2]
We should consider whether it is possible to have a mechanism to connect to multiple targets at the same time using the UART GATT Service. This has come up several times, but I'm afraid it might be a total rewrite of the BLE code ... but it /is/ a problem we should solve at some point, particularly since we're working on V2 anyway?

The idea is to have one central connected via BLE UART to multiple nodes, logging all incoming data.  To simplify things at first, it can be 'read only' on the Central side though, and we can figure out 'writes' later???

**Comment by antonio-openroad** [comment]
Multiple UART connections implemented on the new Swift3 branch. 
Read and write modes available
