### ISSUE TITLE
Return key of Filter UITextField should resign first responder on click

### ISSUE THREAD

**Issue by edorphy** [adafruit/Bluefruit_LE_Connect_v2#21]
Observed: When the user enters a name to filter, the keyboard does not dismiss when the return key is clicked.
Expected: The keyboard will dismiss

Quick Fix:
Implement the UITextFieldDelegate and setup the keyboard to show a done button. In the callback, resign first responder on the textField in the callback.

**Comment by antonio-openroad** [comment]
Thanks for reporting the bug
