### ISSUE TITLE
None of your accounts are a member of '2X94RM7457'

### ISSUE THREAD

**Issue by trungdn** [adafruit/Bluefruit_LE_Connect_v2#27]
When I run the code on Xcode it has this below errors. 
I have paid apple account. What should I do to avoid this errors.

Thank you very much

Showing Recent Issues
Check dependencies

None of your accounts are a member of '2X94RM7457':  An unexpected error occurred. Xcode cannot find a team matching '2X94RM7457'.
No profiles for 'com.adafruit.bluefruitconnect.watchkitapp.watchkitextension' were found:  Xcode couldn't find a provisioning profile matching 'com.adafruit.bluefruitconnect.watchkitapp.watchkitextension'.
Code signing is required for product type 'WatchKit Extension' in SDK 'watchOS 3.2'

**Comment by antonio-openroad** [comment]
You should configure the project with your account. Use your account on all targets.
(2X94RM7457 is the Adafruit development team)
