### ISSUE TITLE
How is your app organized?

### ISSUE THREAD

**Issue by xt280** [adafruit/Bluefruit_LE_Connect_v2#32]
When I connect to my bluetooth device I see a list of modules:
info 
UART 
Plotter
Pin I/O
Controller
Neopixels
AHRS / Calibration
Thermal Camera
Updates

In the controller folder there seems to be a folder for info, UART, Plotter, Pin I/O, Controller, Neopixels, Thermal Camera. There isn't a folder for AHRS / Calibration or Updates. 

How do you actually populate this list view of modules? Is there any common pattern that you use for modules, any common data that you pass into the modules when a user selects one?

**Comment by antonio-openroad** [comment]
Regarding the controller folder:
- updates is called Dfu
- AHRS / Calibration is called Calibration

Regarding how they are modules list is populated, check the `menuItems` function (PeripheralModulesViewController.swift)
