### ISSUE TITLE
Adding more buttons to controller page

### ISSUE THREAD

**Issue by JVarjassy88** [adafruit/Bluefruit_LE_Connect_v2#33]
Hey,

I am wondering if you might be interested in helping out on our latest not-for-profit music video for Cottonwood Records. I recently built a 7-foot rocket that is going to be used as the main story piece. The rocket is wired with a few hundred Neopixels that I am controlling with the Bluetooth Bluefruit App for iOS. What I am needing is relatively simple and shouldn't require much time, however, it will require someone who has a developer account with apple and app experience. 

WHAT IS NEEDED
1. Switch the button type on the controller page to something that only sends a signal on "push", not "push" and "release".
2. Add more buttons (I can provide a layout for you). All the buttons will be triggered the same, just need more than 8 buttons. Some will turn on lights, others will trigger effects etc.

Please let me know asap if you are will to help out. We are shooting on Friday the 25th, so would need the app Thursday at the latest. Thanks!

Cheers,
-Joel

**Comment by ladyada** [comment]
hiya, we don't do custom work. the only other option is you could *try* to use adafruit.io as a gateway through a phone, then on .io you can create any number of buttons. its a *lot* more coding on your end though and we don't do custom work!
https://learn.adafruit.com/bluefruit-le-connect-for-ios/mqtt
