### ISSUE TITLE
Can't edit my iOS App

### ISSUE THREAD

**Issue by yashjain27** [adafruit/Bluefruit_LE_Connect_v2#40]
says I don't have the support for the iCloud capability

**Comment by devangs3** [comment]
same here, was this resolved?

**Comment by yashjain27** [comment]
No not at all

**Comment by antonio-openroad** [comment]
I don't think this problem is related to the app.
Are you using your own Apple Developer Account for the iCloud settings on Xcode?
You could also just disable the iCloud capability if you are not interested on iCloud features. 

Or am I missing something here?
