### ISSUE TITLE
isDefaultConfigurationAssumed can't do PWM

### ISSUE THREAD

**Issue by MMcM** [adafruit/Bluefruit_LE_Connect_v2#42]
In `initializeDefaultPins`, the "PWM pins" and "Digital pin" cases are identical. Shouldn't the former have `isPWM: true`?

(I found an ancient BlueFruit device while cleaning up and it doesn't work with the newer app.)

**Comment by antonio-openroad** [comment]
Yes, you are right. 
The default "PWM pins" should have isPWM to true

Thanks for reporting it
