### ISSUE TITLE
Build failed (Chart,iosDFULibrary,Cocamqtt)

### ISSUE THREAD

**Issue by Poojamok** [adafruit/Bluefruit_LE_Connect_v2#47]
1.Command compileSwiftSources failed with a nonzero exit code 
2.in iosDFULibrary Swift compile erro (for example value of optional type 'CBPeripheral?'must be unwrapped to refer ...
3.cannot infer contextual base in reference to member 'withResponse'

**Comment by antonio-openroad** [comment]
It looks like you are using Xcode13 (iOS15 SDK) before the project was updated to support it. You should be able compile your current downloaded version with Xcode12.x, or you can update to the latest commit.

The project should be compatible with Xcode 13 from this commit: 60a4d75566fef986417b425ed431129b3b2fabd9

**Comment by Poojamok** [comment]
Thank you for helping
