### ISSUE TITLE
info file issue

### ISSUE THREAD

**Issue by Poojamok** [adafruit/Bluefruit_LE_Connect_v2#48]
App is running on simulator but not on real device and also not archieve. whenever i am trying to running on real device it give me following error, 

** #The value of CFBundleShortVersionString in your WatchKit app's Info.plist (3.6.2) does not match the value in your companion app's Info.plist (3.7.0). These values are required to match.**

could you please help me out.

**Comment by antonio-openroad** [comment]
You can change the app version to 3.6.2 and build number to 52 to make it work.
(Just make sure that the version and build numbers are the same for the 3 targets)

<img width="1190" alt="Screenshot 2022-03-15 at 12 07 04" src="https://user-images.githubusercontent.com/3625420/158365278-afbd1a8f-e995-4455-91ed-9b1374f02f02.png">

**Comment by Poojamok** [comment]
ok got it, thank you so much.
