### ISSUE TITLE
When I build it in Xcode, it always fails with Undefined symbol

### ISSUE THREAD

**Issue by ehawker51** [adafruit/Bluefruit_LE_Connect_v2#55]
43 undefined symbols in total with _xmlNanoFTPInit being the first one.

**Comment by antonio-openroad** [comment]
Make sure that you are using Xcode 14.1 and you are opening the  .xcworkspace file and not the .xcodeproj file.

Are you still getting any undefined symbols?

**Comment by keinsein** [comment]
Hello, I am having the same issue. Using Xcode 14.2 and opening .xcworkspace file

**Comment by keinsein** [comment]
Found the solution. Frameworks libs and libxml2 are miss referenced when you download the code. You must add them in general -> frameworks and click on the new frameworks and add Bluefruit to target membership.

**Comment by antonio-openroad** [comment]
We have added a Github action build the project and verify that the workspace file is correct
