### ISSUE TITLE
Add device filtering to scan results

### ISSUE THREAD

**Issue by microbuilder** [adafruit/Bluefruit_LE_Connect_v2#8]
Add device filtering when scanning:

- Default drop down option: "Show all devices"
- Filter by device name: "Device Name Contains" or "Device Name Equals", matching a substring or a full string
- Filter by address: "Address Contains" or "Address Equals", such as "11:22:33:44:55:66" or "44:55" etc.
- Filter by RSSI level: "RSSI >=" and then a negative numeric value such as '-50' dBm for devices close by, etc.
- Filter by UART service presence: "Has UART Service", "No UART Service"

**Comment by antonio-openroad** [comment]
Added in v2.2.0
(Note: Bluetooth address is not available on iOS devices)
