### ISSUE TITLE
Add raw advertising packet option

### ISSUE THREAD

**Issue by microbuilder** [adafruit/Bluefruit_LE_Connect_v2#9]
When you long click the device name in the scan results list (or click a new icon???), add an option to display the raw advertising packet in a popup which may help debugging some issues with custom advertising packets.

**Comment by antonio-openroad** [comment]
Raw advertising packet is not available on iOS. 
Added advertising packet parsed contents:
- Local Name
- Manufacturer
- Sevices
- Services Data
- Services Overflow
- Tx Power
- Is Connectable
- Solicited service
